const path = require('path');
const AssetTrash = require('../AssetTrash');

/**
 * The plugin module to extract the CSS and source map from asset.
 *
 * @note If webpack mode is `production`, then `scss-loader` minifies the CSS self.
 *  If webpack is in `development` mode, then CSS is pretty formatted.
 */

class CssExtractModule {
  /**
   * Extract CSS and source map from the result of the css-loader.
   *
   * Note: this is the implementation for styles specified in HTML.
   *
   * @note The @import handling in CSS is not supported, e.g.: @import 'assets/css/style.css'.
   * Disable @import at-rules handling in `css-loader`:
   * {
   *   test: /\.(css|scss)$/i,
   *   use: [
   *     {
   *       loader: 'css-loader'
   *       options: {
   *         import: false, // disable @import at-rules handling
   *       },
   *     },
   *     'sass-loader',
   *   ],
   * },
   *
   * @param {Compilation} compilation
   * @param {Array<[]>} data The data generated by `css-loader`.
   * @param {string} assetFile The output filename of css.
   * @param {boolean} inline Whether the css should be inlined.
   * @returns {string}
   */
  static apply(compilation, { data, assetFile, inline }) {
    const { compiler } = compilation;
    const { RawSource, ConcatSource } = compiler.webpack.sources;
    const { devtool } = compiler.options;
    const isInlineSourceMap = devtool && devtool.startsWith('inline-');
    const sourceMaps = [];

    let result = '';
    let contentMapping = '';
    let hasMapping = false;
    let mapFile;

    for (const item of data) {
      if (!Array.isArray(item)) continue;

      let [sourceFile, content, media, sourceMap, supports, layer] = item;

      // TODO: refactor the code using the ConcatSource and SourceMapSource as in applyForImportedStyle()

      if (result) result += '\n';

      // when in SCSS is used import of CSS file, like `@import url('./style.css');`
      // then `sourceFile` is null and `content` contains the output CSS filename
      if (sourceFile == null && content.endsWith('.css')) {
        result += `@import url(${content});`;
        continue;
      }

      result += content;

      if (sourceMap) {
        if (isInlineSourceMap || inline) {
          const base64 = Buffer.from(JSON.stringify(sourceMap)).toString('base64');
          contentMapping += '\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,' + base64 + ' */';
        } else {
          sourceMaps.push(sourceMap);
        }
        hasMapping = true;
      }
    }

    if (hasMapping) {
      if (isInlineSourceMap || inline) {
        result += contentMapping;
      } else {
        // if style file is specified in HTML, then should be only one sourceMap pro file
        const sourceMap = sourceMaps[0];
        sourceMap.file = path.basename(assetFile);
        const rawSourceMap = new RawSource(JSON.stringify(sourceMap));

        mapFile = assetFile + '.map';
        result += `\n/*# sourceMappingURL=${path.basename(mapFile)} */`;
        compilation.emitAsset(mapFile, rawSourceMap);
      }
    }

    if (inline) {
      // don't generate css file for inlined styles
      AssetTrash.add(assetFile);
    }

    return result;
  }

  /**
   * Extract CSS and source map from the result of the css-loader.
   *
   * Note: this is the implementation for styles imported in a JavaScript file.
   *
   * @param {Compilation} compilation
   * @param {Array<[]>} data The data generated by `css-loader`.
   * @param {string} assetFile The output filename of css.
   * @param {boolean} inline Whether the css should be inlined.
   * @param {Function} update The callback to replace in url() the raw request with the output filename.
   * @returns {string}
   */
  static applyForImportedStyle(compilation, { data, assetFile, inline }, update) {
    const { compiler } = compilation;
    const { ConcatSource, SourceMapSource } = compiler.webpack.sources;
    const source = new ConcatSource();
    const hasUpdate = typeof update === 'function';

    for (const item of data) {
      if (!Array.isArray(item)) continue;

      let [sourceFile, content, media, sourceMap, supports, layer] = item;

      if (hasUpdate) {
        content = update(content);
      }

      if (sourceMap) {
        source.add(new SourceMapSource(content, sourceFile, JSON.stringify(sourceMap)));
      } else {
        source.add(content);
      }
    }

    if (inline) {
      // don't generate css file for inlined styles
      AssetTrash.add(assetFile);
    }

    return source;
  }
}

module.exports = CssExtractModule;
